# Generated by Django 6.0 on 2026-01-13 12:11

import mimetypes
import os
from django.db import migrations, models


def set_mime_types(apps, schema_editor):
    ScribeFile = apps.get_model('care_scribe', 'ScribeFile')

    for scribe_file in ScribeFile.objects.filter(mime_type__isnull=True) | ScribeFile.objects.filter(mime_type=''):
        extension = os.path.splitext(scribe_file.internal_name)[1].lower()

        if scribe_file.file_type == 1:  # SCRIBE_AUDIO
            mime_type = mimetypes.guess_type(f"file{extension}")[0]
            if not mime_type or not mime_type.startswith('audio/'):
                mime_type = 'audio/mpeg'
            scribe_file.mime_type = mime_type

        elif scribe_file.file_type == 2:  # SCRIBE_DOCUMENT
            mime_type = mimetypes.guess_type(f"file{extension}")[0]
            if not mime_type or not mime_type.startswith('image/'):
                mime_type = 'image/jpeg'
            scribe_file.mime_type = mime_type

        else:
            mime_type = mimetypes.guess_type(f"file{extension}")[0]
            scribe_file.mime_type = mime_type or 'application/octet-stream'

        scribe_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0011_scribefile_mime_type'),
    ]

    operations = [
        migrations.RunPython(set_mime_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='scribefile',
            name='mime_type',
            field=models.CharField(max_length=200),
        ),
    ]
