# Generated by Django 6.0 on 2026-01-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0011_scribefile_mime_type'),
        ('emr', '0052_account_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='requested_in_questionnaires',
            field=models.ManyToManyField(blank=True, related_name='scribes', to='emr.questionnaire'),
        ),
    ]
