# Generated by Django 6.0 on 2026-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0011_scribefile_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribe',
            name='live',
            field=models.BooleanField(default=False, help_text='Whether this is a live transcription scribe'),
        ),
        migrations.AddField(
            model_name='scribequota',
            name='enable_live_transcription',
            field=models.BooleanField(default=False, help_text='Whether the user/facility is allowed to use live transcription'),
        ),
    ]
