# Generated by Django 6.0 on 2026-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_scribe', '0012_scribe_transcript_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribequota',
            name='allow_notes_scribe',
            field=models.BooleanField(default=False, help_text='Whether the user/facility is allowed to use transcript-only scribes'),
        ),
        migrations.AddField(
            model_name='scribequota',
            name='allow_scribe',
            field=models.BooleanField(default=False, help_text='Whether the user/facility is allowed to use normal (form-fill) scribes'),
        ),
    ]
